/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BundleEditor: typeof import('./components/bundle-editor.vue')['default']
    BundleFilesEditor: typeof import('./components/bundle-files-editor.vue')['default']
    ObjectEditor: typeof import('./components/object-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZodiosApi: typeof import('./components/zodios-api.vue')['default']
  }
}
