/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnEvent: typeof import('./components/btn/btn-event.vue')['default']
    BtnGatewayDownloadBackup: typeof import('./components/btn/btn-gateway-download-backup.vue')['default']
    BtnGatewayEditName: typeof import('./components/btn/btn-gateway-edit-name.vue')['default']
    BtnLogin: typeof import('./components/btn/btn-login.vue')['default']
    BtnRoundedCircle: typeof import('./components/btn/btn-rounded-circle.vue')['default']
    BundleEditor: typeof import('./components/bundle-editor/bundle-editor.vue')['default']
    BundleEditorFiles: typeof import('./components/bundle-editor/bundle-editor-files.vue')['default']
    BundleEditorInfo: typeof import('./components/bundle-editor/bundle-editor-info.vue')['default']
    BundleEditorSignatures: typeof import('./components/bundle-editor/bundle-editor-signatures.vue')['default']
    BundleEditorV2: typeof import('./components/bundle-editor-v2/bundle-editor-v2.vue')['default']
    BundleEditorValidation: typeof import('./components/bundle-editor/bundle-editor-validation.vue')['default']
    CardAuthChallenge: typeof import('./components/card/card-auth-challenge.vue')['default']
    CardFileUpload: typeof import('./components/card/card-file-upload.vue')['default']
    CardGateway: typeof import('./components/card/card-gateway.vue')['default']
    ChipDdfHash: typeof import('./components/chip/chip-ddf-hash.vue')['default']
    ChipDdfPolicy: typeof import('./components/chip/chip-ddf-policy.vue')['default']
    ChipGatewayState: typeof import('./components/chip/chip-gateway-state.vue')['default']
    ChipSignatures: typeof import('./components/chip/chip-signatures.vue')['default']
    ChipUser: typeof import('./components/chip/chip-user.vue')['default']
    FormGatewayCredentials: typeof import('./components/form/form-gateway-credentials.vue')['default']
    GatewayBadge: typeof import('./components/gateway-badge.vue')['default']
    GatewayData: typeof import('./components/provider/gateway-data.vue')['default']
    InputRestClientParam: typeof import('./components/form/input-rest-client-param.vue')['default']
    ListBundles: typeof import('./components/list-bundles.vue')['default']
    ListDevices: typeof import('./components/list/list-devices.vue')['default']
    ListItemDevice: typeof import('./components/list/list-item-device.vue')['default']
    ListSupportedDevices: typeof import('./components/list/list-supported-devices.vue')['default']
    NavSidebarLevelOne: typeof import('./components/nagivation/nav-sidebar-level-one.vue')['default']
    NavSidebarLevelTwo: typeof import('./components/nagivation/nav-sidebar-level-two.vue')['default']
    NavSidebarLevelTwoGateway: typeof import('./components/nagivation/nav-sidebar-level-two-gateway.vue')['default']
    NavTopbarDetails: typeof import('./components/nagivation/nav-topbar-details.vue')['default']
    NavTopbarGlobal: typeof import('./components/nagivation/nav-topbar-global.vue')['default']
    ObjectEditor: typeof import('./components/object-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectGateway: typeof import('./components/select/select-gateway.vue')['default']
    TableCollection: typeof import('./components/table-collection.vue')['default']
    UseTimeAgo: typeof import('@vueuse/components')['UseTimeAgo']
    VueMarkdown: typeof import('markdown-vue')['default']
    VueMonacoEditor: typeof import('@guolao/vue-monaco-editor')['VueMonacoEditor']
  }
}
