/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app-bar.vue')['default']
    BtnRoundedCircle: typeof import('./components/btn-rounded-circle.vue')['default']
    BundleEditor: typeof import('./components/bundle-editor.vue')['default']
    BundleFilesEditor: typeof import('./components/bundle-files-editor.vue')['default']
    BundleSignaturesEditor: typeof import('./components/bundle-signatures-editor.vue')['default']
    ListBundles: typeof import('./components/list-bundles.vue')['default']
    LoginButton: typeof import('./components/login-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableCollection: typeof import('./components/table-collection.vue')['default']
    UserChip: typeof import('./components/user-chip.vue')['default']
    UserChipList: typeof import('./components/user-chip-list.vue')['default']
  }
}
