/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnEvent: typeof import('./components/btn/btn-event.vue')['default']
    BtnLogin: typeof import('./components/btn/btn-login.vue')['default']
    BtnRoundedCircle: typeof import('./components/btn/btn-rounded-circle.vue')['default']
    BundleEditor: typeof import('./components/bundle-editor/bundle-editor.vue')['default']
    BundleEditorFiles: typeof import('./components/bundle-editor/bundle-editor-files.vue')['default']
    BundleEditorSignatures: typeof import('./components/bundle-editor/bundle-editor-signatures.vue')['default']
    CardGateway: typeof import('./components/card/card-gateway.vue')['default']
    ChipGatewayState: typeof import('./components/chip/chip-gateway-state.vue')['default']
    ChipUser: typeof import('./components/chip/chip-user.vue')['default']
    ChipUserList: typeof import('./components/chip/chip-user-list.vue')['default']
    Drafter: typeof import('./components/drafter.vue')['default']
    FormGatewayCredentials: typeof import('./components/form/form-gateway-credentials.vue')['default']
    GatewayBadge: typeof import('./components/gateway-badge.vue')['default']
    ListBundles: typeof import('./components/list-bundles.vue')['default']
    ListDevices: typeof import('./components/list/list-devices.vue')['default']
    ListItemDevice: typeof import('./components/list/list-item-device.vue')['default']
    NavSidebarLevelOne: typeof import('./components/nagivation/nav-sidebar-level-one.vue')['default']
    NavSidebarLevelTwo: typeof import('./components/nagivation/nav-sidebar-level-two.vue')['default']
    NavSidebarLevelTwoGateway: typeof import('./components/nagivation/nav-sidebar-level-two-gateway.vue')['default']
    NavTopbarDetails: typeof import('./components/nagivation/nav-topbar-details.vue')['default']
    NavTopbarGlobal: typeof import('./components/nagivation/nav-topbar-global.vue')['default']
    ObjectEditor: typeof import('./components/object-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotGatewayState: typeof import('./components/spot/spot-gateway-state.vue')['default']
    TableCollection: typeof import('./components/table-collection.vue')['default']
    ZodiosApi: typeof import('./components/zodios-api.vue')['default']
  }
}
