packages:
  - packages/*
  - packages/store/packages/*
  - '!**/.vscode-text-web/**'

ignoredBuiltDependencies:
  - isolated-vm

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - argon2
  - esbuild
  - oracledb
  - sharp
  - vue-demi
