/**
 * This file is automatically generated by the `@indirectus/cli` package.
 * Follow the package's instruction to update this file with the latest schema.
 */

import type * as Directus from "@directus/sdk";
import type { Query as Query$ } from "@directus/sdk";
import {
  readSingleton as readSingleton$,
  readItems as readItems$,
  readItem as readItem$,
} from "@directus/sdk";

export type Nullable<T> = T | null;
export type Optional<T> = Nullable<T>;
export type UnknownType<T> = T | unknown;
export type UUID = string;
export type BigInt = number;

/**
 * System collections.
 */

export namespace Collections {
  /**
   * The resolved directus activity collection type.
   *
   */
  export type DirectusActivity = Directus.DirectusActivity<Schema>;

  /**
   * The resolved directus collections collection type.
   *
   */
  export type DirectusCollection = Directus.DirectusCollection<Schema>;

  /**
   * The resolved directus fields collection type.
   *
   */
  export type DirectusField = Directus.DirectusField<Schema>;

  /**
   * The resolved directus files collection type.
   *
   */
  export type DirectusFile = Directus.DirectusFile<Schema>;

  /**
   * The resolved directus folders collection type.
   *
   */
  export type DirectusFolder = Directus.DirectusFolder<Schema>;

  /**
   * The resolved directus permissions collection type.
   *
   */
  export type DirectusPermission = Directus.DirectusPermission<Schema>;

  /**
   * The resolved directus presets collection type.
   *
   */
  export type DirectusPreset = Directus.DirectusPreset<Schema>;

  /**
   * The resolved directus relations collection type.
   *
   */
  export type DirectusRelation = Directus.DirectusRelation<Schema>;

  /**
   * The resolved directus revisions collection type.
   *
   */
  export type DirectusRevision = Directus.DirectusRevision<Schema>;

  /**
   * The resolved directus roles collection type.
   *
   */
  export type DirectusRole = Directus.DirectusRole<Schema>;

  /**
   * The resolved directus settings collection type.
   *
   */
  export type DirectusSettings = Directus.DirectusSettings<Schema>;

  /**
   * The extra fields added to the directus users collection.
   *
   */
  export interface ExtraDirectusUser {
    private_key: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "directus_users";
            field: "private_key";
            type: "string";
            schema: {
              name: "private_key";
              table: "directus_users";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 40;
              collection: "directus_users";
              field: "private_key";
              special: null;
              interface: "input";
              options: null;
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 1;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 40;
          collection: "directus_users";
          field: "private_key";
          special: null;
          interface: "input";
          options: null;
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 1;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    public_key: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "directus_users";
            field: "public_key";
            type: "string";
            schema: {
              name: "public_key";
              table: "directus_users";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 39;
              collection: "directus_users";
              field: "public_key";
              special: null;
              interface: "input";
              options: null;
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 2;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 39;
          collection: "directus_users";
          field: "public_key";
          special: null;
          interface: "input";
          options: null;
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 2;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    avatar_url: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "directus_users";
            field: "avatar_url";
            type: "string";
            schema: {
              name: "avatar_url";
              table: "directus_users";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 38;
              collection: "directus_users";
              field: "avatar_url";
              special: null;
              interface: "input";
              options: null;
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 3;
              width: "full";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 38;
          collection: "directus_users";
          field: "avatar_url";
          special: null;
          interface: "input";
          options: null;
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 3;
          width: "full";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
  }

  /**
   * The resolved directus users collection type.
   *
   */
  export type DirectusUser = Directus.DirectusUser<Schema>;

  /**
   * The resolved directus webhooks collection type.
   *
   */
  export type DirectusWebhook = Directus.DirectusWebhook<Schema>;

  /**
   * The resolved directus dashboards collection type.
   *
   */
  export type DirectusDashboard = Directus.DirectusDashboard<Schema>;

  /**
   * The resolved directus panels collection type.
   *
   */
  export type DirectusPanel = Directus.DirectusPanel<Schema>;

  /**
   * The resolved directus notifications collection type.
   *
   */
  export type DirectusNotification = Directus.DirectusNotification<Schema>;

  /**
   * The resolved directus shares collection type.
   *
   */
  export type DirectusShare = Directus.DirectusShare<Schema>;

  /**
   * The resolved directus flows collection type.
   *
   */
  export type DirectusFlow = Directus.DirectusFlow<Schema>;

  /**
   * The resolved directus operations collection type.
   *
   */
  export type DirectusOperation = Directus.DirectusOperation<Schema>;

  /**
   * The resolved directus translations collection type.
   *
   */
  export type DirectusTranslation = Directus.DirectusTranslation<Schema>;
}

/**
 * User collections.
 */
export namespace Collections {
  /**
   * The bundles collection.
   */
  export interface Bundles {
    id: UnknownType<{
      schema: {
        raw: {
          collection: "bundles";
          field: "id";
          type: "uuid";
          schema: {
            name: "id";
            table: "bundles";
            data_type: "char";
            default_value: null;
            max_length: 36;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: true;
            is_primary_key: true;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 67;
            collection: "bundles";
            field: "id";
            special: ["uuid"];
            interface: "input";
            options: null;
            display: null;
            display_options: null;
            readonly: true;
            hidden: true;
            sort: 1;
            width: "full";
            translations: null;
            note: null;
            conditions: null;
            required: false;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 67;
        collection: "bundles";
        field: "id";
        special: ["uuid"];
        interface: "input";
        options: null;
        display: null;
        display_options: null;
        readonly: true;
        hidden: true;
        sort: 1;
        width: "full";
        translations: null;
        note: null;
        conditions: null;
        required: false;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    user_created: Optional<Collections.DirectusUser>;
    date_created: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "bundles";
            field: "date_created";
            type: "timestamp";
            schema: {
              name: "date_created";
              table: "bundles";
              data_type: "datetime";
              default_value: null;
              max_length: null;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 69;
              collection: "bundles";
              field: "date_created";
              special: ["date-created", "cast-timestamp"];
              interface: "datetime";
              options: null;
              display: "datetime";
              display_options: {
                relative: true;
              };
              readonly: true;
              hidden: true;
              sort: 3;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 69;
          collection: "bundles";
          field: "date_created";
          special: ["date-created", "cast-timestamp"];
          interface: "datetime";
          options: null;
          display: "datetime";
          display_options: {
            relative: true;
          };
          readonly: true;
          hidden: true;
          sort: 3;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    user_updated: Optional<Collections.DirectusUser>;
    date_updated: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "bundles";
            field: "date_updated";
            type: "timestamp";
            schema: {
              name: "date_updated";
              table: "bundles";
              data_type: "datetime";
              default_value: null;
              max_length: null;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 71;
              collection: "bundles";
              field: "date_updated";
              special: ["date-updated", "cast-timestamp"];
              interface: "datetime";
              options: null;
              display: "datetime";
              display_options: {
                relative: true;
              };
              readonly: true;
              hidden: true;
              sort: 5;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 71;
          collection: "bundles";
          field: "date_updated";
          special: ["date-updated", "cast-timestamp"];
          interface: "datetime";
          options: null;
          display: "datetime";
          display_options: {
            relative: true;
          };
          readonly: true;
          hidden: true;
          sort: 5;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    ddf_uuid: UnknownType<{
      schema: {
        raw: {
          collection: "bundles";
          field: "ddf_uuid";
          type: "string";
          schema: {
            name: "ddf_uuid";
            table: "bundles";
            data_type: "char";
            default_value: null;
            max_length: 36;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: false;
            is_primary_key: false;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 72;
            collection: "bundles";
            field: "ddf_uuid";
            special: null;
            interface: "input";
            options: null;
            display: "raw";
            display_options: null;
            readonly: false;
            hidden: false;
            sort: 6;
            width: "full";
            translations: null;
            note: null;
            conditions: null;
            required: true;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 72;
        collection: "bundles";
        field: "ddf_uuid";
        special: null;
        interface: "input";
        options: null;
        display: "raw";
        display_options: null;
        readonly: false;
        hidden: false;
        sort: 6;
        width: "full";
        translations: null;
        note: null;
        conditions: null;
        required: true;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    product: UnknownType<{
      schema: {
        raw: {
          collection: "bundles";
          field: "product";
          type: "string";
          schema: {
            name: "product";
            table: "bundles";
            data_type: "varchar";
            default_value: null;
            max_length: 255;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: false;
            is_primary_key: false;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 73;
            collection: "bundles";
            field: "product";
            special: null;
            interface: "input";
            options: null;
            display: "raw";
            display_options: null;
            readonly: false;
            hidden: false;
            sort: 7;
            width: "full";
            translations: null;
            note: null;
            conditions: null;
            required: true;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 73;
        collection: "bundles";
        field: "product";
        special: null;
        interface: "input";
        options: null;
        display: "raw";
        display_options: null;
        readonly: false;
        hidden: false;
        sort: 7;
        width: "full";
        translations: null;
        note: null;
        conditions: null;
        required: true;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    tag: Optional<"latest">;
    downloads_count: Optional<number>;
    version: UnknownType<{
      schema: {
        raw: {
          collection: "bundles";
          field: "version";
          type: "string";
          schema: {
            name: "version";
            table: "bundles";
            data_type: "varchar";
            default_value: null;
            max_length: 255;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: false;
            is_primary_key: false;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 74;
            collection: "bundles";
            field: "version";
            special: null;
            interface: "input";
            options: null;
            display: "raw";
            display_options: null;
            readonly: false;
            hidden: false;
            sort: 10;
            width: "half";
            translations: null;
            note: null;
            conditions: null;
            required: true;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 74;
        collection: "bundles";
        field: "version";
        special: null;
        interface: "input";
        options: null;
        display: "raw";
        display_options: null;
        readonly: false;
        hidden: false;
        sort: 10;
        width: "half";
        translations: null;
        note: null;
        conditions: null;
        required: true;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    version_deconz: UnknownType<{
      schema: {
        raw: {
          collection: "bundles";
          field: "version_deconz";
          type: "string";
          schema: {
            name: "version_deconz";
            table: "bundles";
            data_type: "varchar";
            default_value: null;
            max_length: 255;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: false;
            is_primary_key: false;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 75;
            collection: "bundles";
            field: "version_deconz";
            special: null;
            interface: "input";
            options: null;
            display: "raw";
            display_options: null;
            readonly: false;
            hidden: false;
            sort: 11;
            width: "half";
            translations: null;
            note: null;
            conditions: null;
            required: true;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 75;
        collection: "bundles";
        field: "version_deconz";
        special: null;
        interface: "input";
        options: null;
        display: "raw";
        display_options: null;
        readonly: false;
        hidden: false;
        sort: 11;
        width: "half";
        translations: null;
        note: null;
        conditions: null;
        required: true;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    bundle: Optional<Collections.DirectusFile>;
    device_identifiers: BundlesDeviceIdentifiers;
  }

  /**
   * The bundles device identifiers collection.
   */
  export interface BundlesDeviceIdentifiers {
    id: number;
    bundles_id: Optional<Bundles>;
    device_identifiers_id: Optional<DeviceIdentifiers>;
  }

  /**
   * The device identifiers collection.
   */
  export interface DeviceIdentifiers {
    id: UnknownType<{
      schema: {
        raw: {
          collection: "device_identifiers";
          field: "id";
          type: "uuid";
          schema: {
            name: "id";
            table: "device_identifiers";
            data_type: "char";
            default_value: null;
            max_length: 36;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: true;
            is_primary_key: true;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 63;
            collection: "device_identifiers";
            field: "id";
            special: ["uuid"];
            interface: "input";
            options: null;
            display: null;
            display_options: null;
            readonly: true;
            hidden: true;
            sort: 1;
            width: "full";
            translations: null;
            note: null;
            conditions: null;
            required: false;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 63;
        collection: "device_identifiers";
        field: "id";
        special: ["uuid"];
        interface: "input";
        options: null;
        display: null;
        display_options: null;
        readonly: true;
        hidden: true;
        sort: 1;
        width: "full";
        translations: null;
        note: null;
        conditions: null;
        required: false;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    manufacturer: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "device_identifiers";
            field: "manufacturer";
            type: "string";
            schema: {
              name: "manufacturer";
              table: "device_identifiers";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 64;
              collection: "device_identifiers";
              field: "manufacturer";
              special: null;
              interface: "input";
              options: {
                iconLeft: null;
              };
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 2;
              width: "full";
              translations: null;
              note: null;
              conditions: null;
              required: true;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 64;
          collection: "device_identifiers";
          field: "manufacturer";
          special: null;
          interface: "input";
          options: {
            iconLeft: null;
          };
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 2;
          width: "full";
          translations: null;
          note: null;
          conditions: null;
          required: true;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    model: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "device_identifiers";
            field: "model";
            type: "string";
            schema: {
              name: "model";
              table: "device_identifiers";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 65;
              collection: "device_identifiers";
              field: "model";
              special: null;
              interface: "input";
              options: null;
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 3;
              width: "full";
              translations: null;
              note: null;
              conditions: null;
              required: true;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 65;
          collection: "device_identifiers";
          field: "model";
          special: null;
          interface: "input";
          options: null;
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 3;
          width: "full";
          translations: null;
          note: null;
          conditions: null;
          required: true;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    bundles: BundlesDeviceIdentifiers;
  }

  /**
   * The environment collection.
   */
  export interface Environment {
    id: UnknownType<{
      schema: {
        raw: {
          collection: "environment";
          field: "id";
          type: "uuid";
          schema: {
            name: "id";
            table: "environment";
            data_type: "char";
            default_value: null;
            max_length: 36;
            numeric_precision: null;
            numeric_scale: null;
            is_generated: false;
            generation_expression: null;
            is_nullable: false;
            is_unique: true;
            is_primary_key: true;
            has_auto_increment: false;
            foreign_key_column: null;
            foreign_key_table: null;
          };
          meta: {
            id: 28;
            collection: "environment";
            field: "id";
            special: ["uuid"];
            interface: "input";
            options: null;
            display: null;
            display_options: null;
            readonly: true;
            hidden: true;
            sort: 1;
            width: "full";
            translations: null;
            note: null;
            conditions: null;
            required: false;
            group: null;
            validation: null;
            validation_message: null;
          };
        };
        raw_relation: null;
      };
      meta: {
        id: 28;
        collection: "environment";
        field: "id";
        special: ["uuid"];
        interface: "input";
        options: null;
        display: null;
        display_options: null;
        readonly: true;
        hidden: true;
        sort: 1;
        width: "full";
        translations: null;
        note: null;
        conditions: null;
        required: false;
        group: null;
        validation: null;
        validation_message: null;
      };
    }>;
    user_created: Optional<Collections.DirectusUser>;
    date_created: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "environment";
            field: "date_created";
            type: "timestamp";
            schema: {
              name: "date_created";
              table: "environment";
              data_type: "datetime";
              default_value: null;
              max_length: null;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 30;
              collection: "environment";
              field: "date_created";
              special: ["date-created", "cast-timestamp"];
              interface: "datetime";
              options: null;
              display: "datetime";
              display_options: {
                relative: true;
              };
              readonly: true;
              hidden: true;
              sort: 3;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 30;
          collection: "environment";
          field: "date_created";
          special: ["date-created", "cast-timestamp"];
          interface: "datetime";
          options: null;
          display: "datetime";
          display_options: {
            relative: true;
          };
          readonly: true;
          hidden: true;
          sort: 3;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    user_updated: Optional<Collections.DirectusUser>;
    date_updated: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "environment";
            field: "date_updated";
            type: "timestamp";
            schema: {
              name: "date_updated";
              table: "environment";
              data_type: "datetime";
              default_value: null;
              max_length: null;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 32;
              collection: "environment";
              field: "date_updated";
              special: ["date-updated", "cast-timestamp"];
              interface: "datetime";
              options: null;
              display: "datetime";
              display_options: {
                relative: true;
              };
              readonly: true;
              hidden: true;
              sort: 5;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 32;
          collection: "environment";
          field: "date_updated";
          special: ["date-updated", "cast-timestamp"];
          interface: "datetime";
          options: null;
          display: "datetime";
          display_options: {
            relative: true;
          };
          readonly: true;
          hidden: true;
          sort: 5;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    secret: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "environment";
            field: "secret";
            type: "string";
            schema: {
              name: "secret";
              table: "environment";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 33;
              collection: "environment";
              field: "secret";
              special: null;
              interface: "input";
              options: {
                iconLeft: "password";
                masked: true;
              };
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 6;
              width: "full";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 33;
          collection: "environment";
          field: "secret";
          special: null;
          interface: "input";
          options: {
            iconLeft: "password";
            masked: true;
          };
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 6;
          width: "full";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    auth_github_default_role_id: Optional<DirectusRole>;
    auth_github_client_id: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "environment";
            field: "auth_github_client_id";
            type: "string";
            schema: {
              name: "auth_github_client_id";
              table: "environment";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 35;
              collection: "environment";
              field: "auth_github_client_id";
              special: null;
              interface: "input";
              options: null;
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 9;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 35;
          collection: "environment";
          field: "auth_github_client_id";
          special: null;
          interface: "input";
          options: null;
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 9;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
    auth_github_client_secret: Optional<
      UnknownType<{
        schema: {
          raw: {
            collection: "environment";
            field: "auth_github_client_secret";
            type: "string";
            schema: {
              name: "auth_github_client_secret";
              table: "environment";
              data_type: "varchar";
              default_value: null;
              max_length: 255;
              numeric_precision: null;
              numeric_scale: null;
              is_generated: false;
              generation_expression: null;
              is_nullable: true;
              is_unique: false;
              is_primary_key: false;
              has_auto_increment: false;
              foreign_key_column: null;
              foreign_key_table: null;
            };
            meta: {
              id: 34;
              collection: "environment";
              field: "auth_github_client_secret";
              special: null;
              interface: "input";
              options: {
                iconLeft: "password";
                masked: true;
              };
              display: null;
              display_options: null;
              readonly: false;
              hidden: false;
              sort: 10;
              width: "half";
              translations: null;
              note: null;
              conditions: null;
              required: false;
              group: null;
              validation: null;
              validation_message: null;
            };
          };
          raw_relation: null;
        };
        meta: {
          id: 34;
          collection: "environment";
          field: "auth_github_client_secret";
          special: null;
          interface: "input";
          options: {
            iconLeft: "password";
            masked: true;
          };
          display: null;
          display_options: null;
          readonly: false;
          hidden: false;
          sort: 10;
          width: "half";
          translations: null;
          note: null;
          conditions: null;
          required: false;
          group: null;
          validation: null;
          validation_message: null;
        };
      }>
    >;
  }
}

/**
 * System collections.
 */
export interface Schema {
  /**
   * The extended directus users collection.
   */
  directus_users: Collections.ExtraDirectusUser[];
}

/**
 * User collections.
 */
export interface Schema {
  /**
   * The bundles collection.
   */
  bundles: Collections.Bundles[];

  /**
   * The bundles device identifiers collection.
   */
  bundles_device_identifiers: Collections.BundlesDeviceIdentifiers[];

  /**
   * The device identifiers collection.
   */
  device_identifiers: Collections.DeviceIdentifiers[];

  /**
   * The environment collection.
   */
  environment: Collections.Environment;
}

/**
 * Helper functions
 */

/**
 * List bundles items.
 */
export function listBundles<
  const Query extends Query$<Schema, Collections.Bundles>,
>(query?: Query) {
  return readItems$<Schema, "bundles", Query>("bundles", query);
}

/**
 * Gets a single known bundles item by id.
 */
export function readBundles<
  const Query extends Query$<Schema, Collections.Bundles>,
>(key: string | number, query?: Query) {
  return readItem$<Schema, "bundles", Query>("bundles", key, query);
}

/**
 * List bundles device identifiers items.
 */
export function listBundlesDeviceIdentifiers<
  const Query extends Query$<Schema, Collections.BundlesDeviceIdentifiers>,
>(query?: Query) {
  return readItems$<Schema, "bundles_device_identifiers", Query>(
    "bundles_device_identifiers",
    query,
  );
}

/**
 * Gets a single known bundles device identifiers item by id.
 */
export function readBundlesDeviceIdentifiers<
  const Query extends Query$<Schema, Collections.BundlesDeviceIdentifiers>,
>(key: string | number, query?: Query) {
  return readItem$<Schema, "bundles_device_identifiers", Query>(
    "bundles_device_identifiers",
    key,
    query,
  );
}

/**
 * List device identifiers items.
 */
export function listDeviceIdentifiers<
  const Query extends Query$<Schema, Collections.DeviceIdentifiers>,
>(query?: Query) {
  return readItems$<Schema, "device_identifiers", Query>(
    "device_identifiers",
    query,
  );
}

/**
 * Gets a single known device identifiers item by id.
 */
export function readDeviceIdentifiers<
  const Query extends Query$<Schema, Collections.DeviceIdentifiers>,
>(key: string | number, query?: Query) {
  return readItem$<Schema, "device_identifiers", Query>(
    "device_identifiers",
    key,
    query,
  );
}

/**
 * Reads the environment singleton.
 */
export function getEnvironment<
  const Query extends Query$<Schema, Collections.Environment>,
>(query?: Query) {
  return readSingleton$<Schema, "environment", Query>("environment", query);
}
