export const subDevicesTypes = [
  '$TYPE_AIR_PURIFIER',
  '$TYPE_AIR_QUALITY_SENSOR',
  '$TYPE_ALARM_SENSOR',
  '$TYPE_BATTERY_SENSOR',
  '$TYPE_COLOR_DIMMABLE_LIGHT',
  '$TYPE_COLOR_LIGHT',
  '$TYPE_COLOR_TEMPERATURE_LIGHT',
  '$TYPE_CONSUMPTION_SENSOR',
  '$TYPE_DIMMABLE_LIGHT',
  '$TYPE_DIMMABLE_PLUGIN_UNIT',
  '$TYPE_DIMMER_SWITCH',
  '$TYPE_DOOR_LOCK_CONTROLLER',
  '$TYPE_DOOR_LOCK',
  '$TYPE_EXTENDED_COLOR_LIGHT',
  '$TYPE_FIRE_SENSOR',
  '$TYPE_HUMIDITY_SENSOR',
  '$TYPE_LIGHT_LEVEL_SENSOR',
  '$TYPE_ON_OFF_LIGHT',
  '$TYPE_ON_OFF_OUTPUT',
  '$TYPE_ON_OFF_PLUGIN_UNIT',
  '$TYPE_OPEN_CLOSE_SENSOR',
  '$TYPE_POWER_SENSOR',
  '$TYPE_PRESENCE_SENSOR',
  '$TYPE_PRESSURE_SENSOR',
  '$TYPE_RANGE_EXTENDER',
  '$TYPE_RELATIVE_ROTARY',
  '$TYPE_SMART_PLUG',
  '$TYPE_SPECTRAL_SENSOR',
  '$TYPE_SWITCH',
  '$TYPE_TEMPERATURE_SENSOR',
  '$TYPE_THERMOSTAT',
  '$TYPE_VIBRATION_SENSOR',
  '$TYPE_WARNING_DEVICE',
  '$TYPE_WATER_LEAK_SENSOR',
  '$TYPE_WINDOW_COVERING_DEVICE',
  '$TYPE_ZGP_SWITCH',
  'ZHAAirPurifier',
  'ZHAAirQuality',
  'ZHAAlarm',
  'ZHABattery',
  'Color dimmable light',
  'Color light',
  'Color temperature light',
  'ZHAConsumption',
  'Dimmable light',
  'Dimmable plug-in unit',
  'Dimmer switch',
  'Door lock controller',
  'Door Lock',
  'Extended color light',
  'ZHAFire',
  'ZHAHumidity',
  'ZHALightLevel',
  'On/Off light',
  'On/Off output',
  'On/Off plug-in unit',
  'ZHAOpenClose',
  'ZHAPower',
  'ZHAPresence',
  'ZHAPressure',
  'Range extender',
  'ZHARelativeRotary',
  'Smart plug',
  'ZHASpectral',
  'ZHASwitch',
  'ZHATemperature',
  'ZHAThermostat',
  'ZHAVibration',
  'Warning device',
  'ZHAWater',
  'Window covering device',
  'ZGPSwitch',
  'ZHAAncillaryControl',
  'ZHATime',
  'ZHACarbonMonoxide',
  'ZHADoorLock',
] as const
