version: '3'
services:
  directus:
    container_name: ddf-store
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      - database:/directus/database
      - uploads:/directus/uploads
    env_file:
      - .env
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      KEY: ${KEY}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      TELEMETRY: ${TELEMETRY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    stdin_open: true
    tty: true
volumes:
  database:
  uploads: