version: '3'
services:
  ddfstore:
    build:
      context: ../../.
      dockerfile: packages/store/Dockerfile
    ports:
      - 8056:8055
    volumes:
      - ddf-store-database:/directus/database
      - ddf-store-uploads:/directus/uploads
    env_file:
      - .env
      - .env.local
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
    stdin_open: true
    tty: true
volumes:
  ddf-store-database:
  ddf-store-uploads: