version: '3'
services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ddf-store-database:/directus/database
      - ddf-store-uploads:/directus/uploads
    env_file:
      - .env
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      KEY: ${KEY}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      AUTH_PROVIDERS: ${AUTH_PROVIDERS}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      AUTH_GITHUB_DEFAULT_ROLE_ID: ${AUTH_GITHUB_DEFAULT_ROLE_ID}
      TELEMETRY: ${TELEMETRY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    stdin_open: true
    tty: true
volumes:
  ddf-store-database:
  ddf-store-uploads: